### PR TITLE
Empty input override fields should be null

### PR DESCRIPTION
**Pull request by minhhau99**

### CODE REVIEW

**Comment by CanuckMarc** [comment]
@minhhau99 

This fix doesn't work.   Only seems to work on the `const-num` node.  

These ones work:
image

These ones don't (and others):
image


Possibly related issue: https://github.com/NubeIO/rubix-ui/issues/559

**Comment by minhhau99** [comment]
Hi @CanuckMarc 
I fixed it according to what you said, please check it for me it is working as you want

**Comment by CanuckMarc** [comment]
@minhhau99 

Still not working.  The root of the issue is that a manually cleared/empty numeric input field's value should be the same as `null`, but instead it is being treated as a `0`.  None of the nodes in your screenshot have a cleared input field.

image

**Comment by minhhau99** [comment]
Is this correct what you mean?

https://user-images.githubusercontent.com/120352098/220819145-91dedda3-7965-496f-8da1-4ff7eef00885.mov

**Comment by CanuckMarc** [comment]
Ya, perfect! thanks

**Pull request merged**
